/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./components/AboutPage.vue')['default']
    AuthPage: typeof import('./components/AuthPage.vue')['default']
    ContactPage: typeof import('./components/ContactPage.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HobbiesPage: typeof import('./components/HobbiesPage.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
